# Generated by Django 3.2.22 on 2023-10-15 06:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('amazon', '0006_products_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='owner',
        ),
    ]
