# Generated by Django 3.2.22 on 2023-10-15 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amazon', '0007_remove_products_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='owner',
            field=models.CharField(default='none', max_length=100),
        ),
    ]
